### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by aquapi**

### CODE REVIEW

**Comment by aquapi** [comment]
I removed dead projects.

Now we need to add more frameworks and libraries.

**Comment by terrablue** [comment]
Hi, could you please add Primate under Frameworks? https://primatejs.com/blog/release-024

**Comment by aquapi** [comment]
Sure

**Comment by aquapi** [comment]
image
Added @terrablue

**Comment by itsyoboieltr** [comment]
@aquapi Hey, could you please add DBEST stack under boilerplates? :D
https://github.com/itsyoboieltr/dbest-stack

**Comment by aquapi** [comment]
@itsyoboieltr Added

**Pull request merged**
